language: python
before_install:
  - sudo apt-get -y install enchant
install:
  - pip install -r requirements.txt
script: make html

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  local_dir: _build
  github_token: $GITHUB_TOKEN
  on:
    branch: gh-pages
